CREATE TABLE movie1(id int not null, hero_name varchar(20), heroine_name varchar(20) , director_name varchar(20), comedian varchar(20), release_date varchar(20), producer varchar(20), languageofmovie varchar(20), budget bigint unique not null, choreographer varchar(20)); 
SELECT * FROM movie1;
INSERT INTO movie1 values(1,"puneet rajkumar","ramya","yograj bhat","sadhu kokila",1997,"narendra","kannada",1000000,"rudra" );
INSERT INTO movie1 values(2,"shiv rajkumar","radhika","harikrishna","chikkanna",2003,"ramesh singh","kannada",3200000,"ramu" );
INSERT INTO movie1 values(3,"mahesh babu","kajol","sharanu","brahmananda",2010,"rajesh patil","telugu",2500000,"sadashiv" );
INSERT INTO movie1 values(4,"akshay kumar","madhuri dixit","rohit shetty","johny liver",2018,"pramod shetty","hindi",5600000,"karan" );
INSERT INTO movie1 values(5,"vijay thalapathy","rashmika mandanna","prakash raj","akash",2022,"anand rao","tamil",3900000,"vishwa" );
INSERT INTO movie1 values(6,"jiya shankar","kushi hajare","ambareesh","aniketh",2021,"karthik","marathi",1200000,"bheemsen" );
INSERT INTO movie1 values(7,"rakshit shetty","aishany shetty","sadhu","murari rai","2016","paramehwar","kannada",2300000,"sangamesh" );
INSERT INTO movie1 values(8,"prabhas ","anushka shetty","naveen krishna","sai tej ",2020,"lokesh kp","dinesh",5000000,"purushottham" );
INSERT INTO movie1 values(9,"amir khan ","anupama","banargy khan ","ravi kumar ",2018,"manjunath","hindi",9000000,"vinod kumar" );
INSERT INTO movie1 values(10," allu arjun","keerthi suresh","brahmananda ","prakash tej ",2021,"subramanyam","telugu",2000000,"ravi" );
INSERT INTO movie1 values(11,"Tom Cruise","jennifer ","alankit","johny patt",2011,"abrahm","english",4500000,"chris laren" );
INSERT INTO movie1 values(12,"kamal hassan","nayantara","raj kamal","vikram nath",1999,"deepak kumar","tamil",200000,"sanju nirmal" );
INSERT INTO movie1 values(13,"darshan","rachita ram","yograj bhat","tennis krishna",2020,"akash raj","kannada",3200000,"manju kumar" );
INSERT INTO movie1 values(14,"salman khan","kajol","preetham singh","ramkrishna",2015,"karunakar","hindi",5420000,"mukhesh rao" );
INSERT INTO movie1 values(15,"rajkumar","kalpana","s narayan","balayya",1998,"krishna raj","kannada",600000,"prathap kumar" );
INSERT INTO movie1 values(16,"ajay","samantha","shivsagar","vivek",2014,"narayan prasad","tamil",1300000,"shivkumar" );
INSERT INTO movie1 values(17,"sudeep","rakshita","ramu","bullet prakash",2012,"prasanna raj","kannada",400000,"sandeep kumar" );
INSERT INTO movie1 values(18," Robert De Niro","emma watson","yograj bhat","sadhu kokila",1997,"narendra","kannada",1000000,"rudra" );
INSERT INTO movie1 values(19,"karthik","anusuya","ajay kumar","deepak",1999,"anudeep shetty","malayalam",6700000,"sharanu" );
INSERT INTO movie1 values(20,"ganesh","amulya","yograj bhat","sadhu kokila",2022,"ravi kumar","kannada",2300000,"manjunath" );